### ISSUE TITLE
Readback example is broken

### ISSUE THREAD

**Issue by divisuals** [unconed/mathbox#65]
The [readback example](https://mathbox.org/test/readback.html) seems to be broken in the latest release.

If you hover over the points, they don't change colors as expected from older examples. Chrome Debug Tools don't show any errors either.

Long-term, would be great to convert such examples as explicit tests.

**Comment by divisuals** [comment]
FWIW, I played with older builds/ THREE versions and found this cryptic error in the DevTools:
- THREE r118.0 
- MathBox v2.2.0 and v2.2.1 (older builds from last year)

```
WebGLRenderer.js:1275 Uncaught TypeError: material.onBeforeRender is not a function
    at renderObject (WebGLRenderer.js:1275:1)
    at renderObjects (WebGLRenderer.js:1260:1)
    at renderScene (WebGLRenderer.js:1182:1)
    at WebGLRenderer.render (WebGLRenderer.js:1002:1)
    at memo_Memo.render (rendertotexture.js:119:1)
    at readback_Readback.update (readback.js:262:1)
    at Readback.update (readback.js:100:1)
    at Root._trigger (binder.js:121:1)
    at Root.update (root.js:108:1)
    at Context.update (context.js:194:1)
```

Worth a starting point though this is probably low priority, as there are alternate ways to achieve mouseover effects ([Raycaster](https://threejs.org/docs/#api/en/core/Raycaster))

**Comment by ChristopherChudzicki** [comment]
Echoing what @sritchie said in https://github.com/unconed/mathbox/issues/19#issuecomment-1496232760, thanks again for reporting these and sorry for inactivity around fixes. (If you are interested in fixing any of these, let us know. Your digging is helpful either way.)

Like sam, I'm a bit busy in recent weeks, but as he said, do let us know if any of these are impacting you seriously.

**Comment by divisuals** [comment]
Thanks! 

These are not blocking at the moment - I'm just using my ugly, untested workarounds for now.

Will raise issues and create a pull request for any urgent blockers!
